"""adicionando campo status em reserva

Revision ID: 3931926da445
Revises: ba10ac81f0f9
Create Date: 2025-11-15 20:41:51.681955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3931926da445'
down_revision: Union[str, Sequence[str], None] = 'ba10ac81f0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('status', sa.String(length=50), server_default='Aguardando Validação', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'status')
    # ### end Alembic commands ###
