"""migracao inicial

Revision ID: 6d014bdfaf8b
Revises: 
Create Date: 2025-11-15 15:41:57.104910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d014bdfaf8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_agendamento', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('numero_computador', sa.Integer(), nullable=False),
    sa.Column('email_usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_reserva', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(), nullable=False),
    sa.Column('email_usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
