"""adicionando autor em agenda e reserva

Revision ID: 72554d21d2da
Revises: abf6af36a014
Create Date: 2025-12-05 08:58:59.445530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72554d21d2da'
down_revision: Union[str, Sequence[str], None] = 'abf6af36a014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('autor', sa.String(length=50), nullable=False))
    op.add_column('reservas', sa.Column('autor', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'autor')
    op.drop_column('agendamentos', 'autor')
    # ### end Alembic commands ###
