"""adicionando campo changed_by em reserva

Revision ID: 7928ed73092d
Revises: 809ca7a0e6fc
Create Date: 2025-11-20 20:39:21.035084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7928ed73092d'
down_revision: Union[str, Sequence[str], None] = '809ca7a0e6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('changed_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'changed_by')
    # ### end Alembic commands ###
