"""adicionando campo changed em reserva

Revision ID: 809ca7a0e6fc
Revises: 3931926da445
Create Date: 2025-11-20 20:28:54.531558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809ca7a0e6fc'
down_revision: Union[str, Sequence[str], None] = '3931926da445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('changed', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'changed')
    # ### end Alembic commands ###
