"""traduzindo campos e adicionando campo cancelado em reserva

Revision ID: 9ac036e6b75d
Revises: 7928ed73092d
Create Date: 2025-11-20 20:47:41.663339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac036e6b75d'
down_revision: Union[str, Sequence[str], None] = '7928ed73092d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('alterado', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('reservas', sa.Column('alterado_por', sa.String(length=50), nullable=True))
    op.add_column('reservas', sa.Column('cancelado', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.drop_column('reservas', 'changed_by')
    op.drop_column('reservas', 'changed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('changed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.add_column('reservas', sa.Column('changed_by', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('reservas', 'cancelado')
    op.drop_column('reservas', 'alterado_por')
    op.drop_column('reservas', 'alterado')
    # ### end Alembic commands ###
