"""adicionando campo id do google em agendamento e reserva

Revision ID: abf6af36a014
Revises: ae51261704b2
Create Date: 2025-11-21 00:46:41.178855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf6af36a014'
down_revision: Union[str, Sequence[str], None] = 'ae51261704b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.add_column('reservas', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'google_event_id')
    op.drop_column('agendamentos', 'google_event_id')
    # ### end Alembic commands ###
