"""adicionando campo cancelado em agendamentos

Revision ID: ae51261704b2
Revises: 9ac036e6b75d
Create Date: 2025-11-20 22:22:42.378780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae51261704b2'
down_revision: Union[str, Sequence[str], None] = '9ac036e6b75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('cancelado', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'cancelado')
    # ### end Alembic commands ###
