"""removendo horario de reserva

Revision ID: ba10ac81f0f9
Revises: 6d014bdfaf8b
Create Date: 2025-11-15 16:43:40.717636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba10ac81f0f9'
down_revision: Union[str, Sequence[str], None] = '6d014bdfaf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'hora_inicio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('hora_inicio', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
